ALTER TABLE orders ADD COLUMN pack_cents INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN tax_cents INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN other_cents INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN tax_label TEXT NOT NULL DEFAULT 'Duties & taxes';
ALTER TABLE orders ADD COLUMN ship_country TEXT NOT NULL DEFAULT '';
